데이터 분석 역량의 중요성
- 각 산업에서 수집된 데이터에 관한 도메인 지식과 함께 데이터 분석 역량을 갖춘다면 유의미한 정보를 얻을 수 있다
    ex. 산업별 도메인 지식(헬스케어, 금융, 반도체 게임산업, 운송업 등)
    ex. 직무별 도메인 지식(마케터, 기획, 영업, 경영지원)
    ex. 데이터 분석 역량(데이터 전처리 및 시각화)

데이터 분석 과정
: 시각화 분석을 위해 데이터셋의 특징을 파악한 후, 결측값 및 데이터 가공과정의 전처리를 거쳐 데이터를 분석 및 시각화하여 유의미한 결과 발견

# Tensor : 같은 크기의 행렬들(텐서들)을 모아놓은 데이터의 집합

In [2]:
#Array 
# 3 x 2 행렬 구조로 Array 형태 데이터 A, B를 생성하고, + 연산한 Array 구하라
import numpy as np

A = np.array([[2, 3], [4, 5], [6, 7]])
B = np.array([[1, 1], [3, 3], [5, 5]])
A

array([[2, 3],
       [4, 5],
       [6, 7]])

In [3]:
B

array([[1, 1],
       [3, 3],
       [5, 5]])

In [4]:
A + B

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [7]:
#random
#1 ~100 사이 정수 랜덤하게 한 개 추출
import random

np.random.randint(1, 101)
np.random.randint(1, 101, size=2)

array([83, 21])

In [9]:
import pandas as pd

df2 = pd.DataFrame(data = {
    "학번" : [201901, 201902, 202001, 201504, 201402, 201809],
    "이름" : ["은빈", "김우빈", "서강준", "장나라", "김사랑", "최준"],
    "성적" : [70, 90, 80, 100, 75, 79],
    "학점" : ["C", 'A', "B", "A+", "C+", "C+"]},
    columns=["학번", "이름", "성적", "학점"]
)
df2

학번   이름   성적  학점
0  201901   은빈   70   C
1  201902  김우빈   90   A
2  202001  서강준   80   B
3  201504  장나라  100  A+
4  201402  김사랑   75  C+
5  201809   최준   79  C+

In [11]:
df2.index = ['a', 'b', 'c', 'd', 'e', 'f']
df2

학번   이름   성적  학점
a  201901   은빈   70   C
b  201902  김우빈   90   A
c  202001  서강준   80   B
d  201504  장나라  100  A+
e  201402  김사랑   75  C+
f  201809   최준   79  C+